CREATE TABLE ENFERMEIRO(
  ID_ENFERMEIRO INT NOT NULL IDENTITY,
  NOME_ENFERMEIRO VARCHAR(50) NOT NULL ,
  COREN_ENFERMEIRO VARCHAR(14) NOT NULL,
PRIMARY KEY(ID_ENFERMEIRO));

CREATE TABLE CIDADE(
  ID_CIDADE INT NOT NULL IDENTITY,
  NOME_CIDADE VARCHAR(50) NOT NULL,
  UF_CIDADE CHAR(2) NOT NULL,
PRIMARY KEY(ID_CIDADE));


CREATE TABLE VACINA(
  ID_VACINA INT NOT NULL IDENTITY,
  NOME_VACINA VARCHAR(50) NOT NULL,
  DATANASC_VACINA DATE NOT NULL,
  END_VACINA VARCHAR(100) NOT NULL,
  CIDADE_ID_CIDADE INT NOT NULL,
  CPF_VACINA CHAR(11) NOT NULL,
  RG_VACINA CHAR(9) NOT NULL,
  DATA_VACINA DATE NOT NULL,
  TIPO_VACINA CHAR(1) NOT NULL,
  COMORBIDADE_VACINA CHAR(1) NOT NULL,
  GRUPOPRIORI_VACINA CHAR(1) NOT NULL,
  ENFERMEIRO_ID_ENFERMEIRO INT NOT NULL,
PRIMARY KEY(ID_VACINA),
FOREIGN KEY(CIDADE_ID_CIDADE)REFERENCES CIDADE(ID_CIDADE),
FOREIGN KEY(ENFERMEIRO_ID_ENFERMEIRO)REFERENCES ENFERMEIRO(ID_ENFERMEIRO));

